# Generated by Django 3.2.9 on 2021-11-13 05:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True)),
                ('header', models.ImageField(blank=True, upload_to='headers/')),
                ('youtube', models.URLField(blank=True)),
            ],
        ),
    ]
